# Dataset
data_dir: data/imagenet
train_split: train
val_split: val

# Model
teacher_model: vit_base_patch16_clip_quickgelu_224.openai
teacher_pretrained: true
student_model: vit_base_patch16_clip_quickgelu_224.openai
student_pretrained: true

# Batch size
batch_size: 256
validation_batch_size: 256
grad_accum_steps: 1

# System optimizations
amp: true
amp_dtype: bfloat16
torchcompile: inductor

# Optimizer
opt: adamw
weight_decay: 0.01
clip_grad: 1.0
opt_kwargs:
  betas: [0.9, 0.95]

# Learning rate schedule
sched: cosine
sched_on_updates: true
lr: 3e-4
min_lr: 3e-5
warmup_lr: 3e-5
epochs: 2
warmup_epochs: 1

# Augmentation and regularization
train_crop_mode: rkrc
color_jitter: null

# Misc
workers: 24
pin_mem: true
output: output
experiment: clip-vit-b-in1k-e2
project: locality-alignment-ablations
log_wandb: true
